### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by lukalukaluka7000** [lukalukaluka7000/FractalGeometry#1]
Optimizations:
- [x] use glFragCoord
- [x] send quad instead of SW*SH vertices (obviously it is not necessery in fact it is problematic)
- [x] maybe 1-d texture for preetier print
- [x] make a 256x1 texture palette
- [x] add zoom, processInput()

EDIT: in fact, 3rd and 4th are essential because of extremely low (and high) floating values in fragment color, since zoomValue and divStep would be way too low or high. 

So not just prettier print, but correct drawing
